import { Keypair } from "@solana/web3.js";
import bs58 from "bs58";
import { randomUUID } from "crypto";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const vaultKeypair = Keypair.generate();
const vaultKey = bs58.encode(vaultKeypair.secretKey);

const secret = randomUUID();

const toWrite = `# Auto-generated by scripts/setup.ts

VAULT_PRIVATE_KEY="${vaultKey}"
VAULT_PUBLIC_KEY="${vaultKeypair.publicKey.toString()}"
SECRET="${secret}"

RPC="https://api.mainnet-beta.solana.com" # Solana Mainnet, replace with your preferred mainnet RPC if required
# RPC="https://api.devnet.solana.com" # Solana Devnet, ideal for testing and development
# RPC="http://localhost:8899" # Local Solana node, ideal for testing and development
DATABASE_URL="" # Create a new MongoDB database and add the connection string here
AMQP_URL="" # Create a new RabbitMQ instance and add the connection string here
`;

fs.writeFileSync(
  path.join(path.dirname(fileURLToPath(import.meta.url)), "../.env"),
  toWrite
);
